### ISSUE TITLE
App Feedback

### ISSUE THREAD

**Issue by talhaadnan100** [UBC-MDS/Olympics_Medal_Exploration#10]
We really likes your app. It conveys a lot of information in an easy-to-digest manner. The things you've done really well are: 

- Present a world map that conveys the number of medals won, and trend of sport participation.
- Filtering capability for country, type of sport, athlete info and others.
 
Some ideas of improvements identified by our group are: 

- [x] The length of the filter panel can be reduced so that the user doesn't have to scroll to select attributes.
- [x] Word cloud could be it's own separate tab, and include a small description of what it is conveying.
- [x] Also the line chart could be it's own separate tab.

**Comment by HarjyotKaur** [comment]
Thanks for the feeback Talha and Makk, 

We have implemented the suggestions you gave us. 
You can view them here: https://harjyotkaur.shinyapps.io/Olympics_app/
