### ISSUE TITLE
App Feedback - Evan & Zixin

### ISSUE THREAD

**Issue by EvanYathon** [UBC-MDS/Olympics_Medal_Exploration#11]
Hey guys, your app looked great.  Here are some suggestions that we talked about:

- Rename 'No Medal' to 'Participants' or a more descriptive name
- Reactive filtering options; for example if you filter to swimming, then weight/height inputs will dynamically change.
- Perhaps add the age/height/weight histograms to be in a more prominent place - they had lots of good information.
- Title the word cloud to a descriptive name
- Maybe make the line plot have multiple options for the y variable?  
  - For example it could be interesting to see how the height of gold medal gymnasts has changed over the years
- Rename tab names to be more descriptive of their contents

Thanks!  Great job!

**Comment by HarjyotKaur** [comment]
Thanks for the feeback Evan and Zxin.  

We have implemented the suggestions you gave us. 
You can view them here: https://harjyotkaur.shinyapps.io/Olympics_app/
