### ISSUE TITLE
some things we can improve

### ISSUE THREAD

**Issue by shayne-andrews** [UBC-MDS/Olympics_Medal_Exploration#7]
Some of these can be done for milestone2 and some can be left for next week:
- horizontal bar charts for the Sex and Medal variables in the left sidebar
- reduce spacing around map
- sync the filters with the map (heatmap colours)
- choose a more obvious colour scale for the heatmap
- try using dot plots instead of histograms where the dots look like medals (colour = gold/silver/bronze)
- consider whether the timeline graph (below the map) is insightful enough, need to think more about whether each line is a sport or event (or country?), and perhaps making it interactive with extra info on hover
- list of countries is really cumbersome and could be removed if we make the map clickable or focus the dashboard on showing just a few countries at once (and put this list in the left sidebar)

**Comment by HarjyotKaur** [comment]
Mostly all have been taken care of, the rest have been added as a part of milestone2, "furture milestones"
